development:
  adapter: postgresql
  encoding: unicode
  database: mcmuch_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: mcmuch_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: mcmuch
  pool: 5
